### ISSUE TITLE
Skaffold YAML changes not immediately seen by Skaffold tools if not explicitly saved

### ISSUE THREAD

**Issue by ivanporty** [GoogleContainerTools/google-container-tools-intellij#100]
When adding a new change into Skaffold YAML file, for example, new profile or an image change, or even adding a new Skaffold YAML file, tools that rely on file content - Skaffold file search or YAML content may not see the change right away unless file is explicitly saved by `Ctrl-S`. 

We need to find a way to commit the writes or flush the cache before the actions that need up-to-date Skaffold YAML contents.

**Comment by etanshaul** [comment]
> We need to find a way to commit the writes or flush the cache before the actions that need up-to-date Skaffold YAML contents.

or read from the underlying psi representation instead of the file from disk. I wonder if we solved this already in the other plugin

**Comment by etanshaul** [comment]
specifically, we may have solved this when reading the runtime from appengine-web.xml (the runtime for example)

**Comment by ivanporty** [comment]
Sounds good, let me double check it there.

**Comment by ivanporty** [comment]
I see a couple of calls that seems to aim this:
```
FileDocumentManager.getInstance().saveAllDocuments();
PsiFile psiFile = PsiManager.getInstance(project).findFile(virtualFile)
```

I'll double check which one should work for this case.

**Comment by etanshaul** [comment]
Ah yes. I suspect that the first line isn't needed when reading from the PSI system, but I'm not positive.
