### ISSUE TITLE
Skaffold run target validation: validate Skaffold executable before run / during edit

### ISSUE THREAD

**Issue by ivanporty** [GoogleContainerTools/google-container-tools-intellij#117]
Currently we assume Skaffold to be present in the system in order to run its deployment and development configurations. If it's not present, error will be shown (`skaffold` executable not found or similar) after run and nothing else is proposed.

We need to validate presence of Skaffold using current (default system based) executor service and show run configuration as invalid if Skaffold is not present in the system, suggesting to install Skaffold in order to fix it. Later this is going to be further enhanced with managed Skaffold installation.

**Comment by etanshaul** [comment]
we should also probably link to the "prerequisites" section in our GitHub docs in any notification that we surface

**Comment by ivanporty** [comment]
Closed via #158
