### ISSUE TITLE
Make pre-release plugin build available for early access

### ISSUE THREAD

**Issue by ivanporty** [GoogleContainerTools/google-container-tools-intellij#139]
(Originally suggested by @etanshaul)

Currently there is no easy way to install the preliminary version of the plugin for testing and early access before we have it available in Jetbrains repository. We can use Kokoro to automate plugin build (`buildPlugin` build task) and copying the resulting zip distributive into a directory (at the root of the project in a `prerelease` folder for example) on every commit to master. This would avoid the initial build step.

**Comment by patflynn** [comment]
How far off are we from being able to push to jetbrains repo alpha channel?}

**Comment by ivanporty** [comment]
Will be available in alpha channel as part of Cloud Tools plugin after the merge.
