### ISSUE TITLE
Example project didn't prompt for run configuration creation

### ISSUE THREAD

**Issue by etanshaul** [GoogleContainerTools/google-container-tools-intellij#146]
I simply loaded up the spring-boot example project expecting to be prompted to have the k8s run configs created, but they never popped up. Nor were they in the event log.

**Comment by etanshaul** [comment]
Strangely after close the project and re-opening it, I was prompted to create the run configs. I wonder if it has something to do with the first load..the exact steps the first time were:

1) open the example spring boot project
2) sync with maven
3) wait for the run config notification (which didn't come)

**Comment by ivanporty** [comment]
Interesting, this might have something to do with Maven sync - was it auto-sync or manual sync? Was it triggered immediately after `Indexing...` was done after project open?

**Comment by etanshaul** [comment]
I think it was on manual sync but I’m not 100% sure.

I also think I did a sync right away.

**Comment by ivanporty** [comment]
I think I found the reason - when you open a "raw" project not configured as IntelliJ project yet (e.g. Maven and Gradle ones for the first time), modules are not created immediately but project itself is completely initialized. PR to fix this is coming.
