### ISSUE TITLE
Add Skaffold file search across the project

### ISSUE THREAD

**Issue by ivanporty** [GoogleContainerTools/google-container-tools-intellij#37]
Iterate project files, without excluded directories such as module compile output, and use the list of found files to populate drop-down with available Skaffold files in run configurations UI settings.

Part of #7, #12, #13.

**Comment by etanshaul** [comment]
is there a way to configure skaffold to use config files named something other than `skaffold.yaml`? we should probably take that into account early if so.

@loosebazooka any idea?

**Comment by etanshaul** [comment]
also I see a couple ways we can do these:

what I was originally thinking was use to use the framework support mechanism to detect each skaffold.yaml, setting up the run configuration automatically for the user. This is a bit complicated by the fact that we are separating out `run` and `dev` run configs into separate things. @ivanporty what were your thoughts on the direction of this?

**Comment by ivanporty** [comment]
I think it does have a `-f` option and any other file name option may be used. I think we need to implement based on the actual content, not just the name, and use API version, i.e. `apiVersion: skaffold/*`

**Comment by ivanporty** [comment]
I was thinking about avoiding a framework since I don't see any other use for it except a run configuration. Run configuration is pretty independent and works on all IDEs. Later we can think about implementing this as a framework too.

**Comment by etanshaul** [comment]
ah right. framework support / facets all that are IDEA specific. and they do add a lot of complication for the user as well.
