### ISSUE TITLE
Support settings for Skaffold default image repo

### ISSUE THREAD

**Issue by ivanporty** [GoogleContainerTools/google-container-tools-intellij#52]
Skaffold now supports concept of *default image repository*, the one that is used for all Skaffold deployments regardless of what is configured in skaffold configuration for build stage. This allows users to try out other developer pipelines without having to worry about changing build step and image/repo name.

We can add this to individual run configuration or as a global setting.

See https://github.com/GoogleContainerTools/skaffold/pull/1057 for more details.

**Comment by etanshaul** [comment]
+1. was just testing out a non-trivial project and this would be useful. I'm in favor of adding it to the individual run configs
