### ISSUE TITLE
Ensure supported range of IDEs for the plugin

### ISSUE THREAD

**Issue by ivanporty** [GoogleContainerTools/google-container-tools-intellij#61]
While testing Skaffold run configurations support for various IDEs, I found out non-Java IDEs versions 2018.1 and earlier do not have UI DSL classes packaged with them hence causing exceptions when using them for our UI. We either need to decrease range of supported IDEs or change UI back to form builder to allow older IDE versions support.

**Comment by ivanporty** [comment]
I should correct myself, IDEA earlier than 2018.2 does not bundle that either, so either UI DSL or older versions support, all Jetbrains IDEs included. I have no (so far) very strong preferences for UI DSL over form builder, but don't see a big value in keeping older IDE versions as well. WDYT?

**Comment by etanshaul** [comment]
given the upgrade model of intellij and that presumably 2018.3 will come out of EAP soon (and 2019 will likely follow) I'm ok with 2018.2 and up.
