### ISSUE TITLE
Skaffold run configs do not see shell environment variables (PATH) on Linux when IDE starts from desktop

### ISSUE THREAD

**Issue by etanshaul** [GoogleContainerTools/google-container-tools-intellij#67]
```
time="2018-11-01T12:46:38-04:00" level=fatal msg="exiting dev mode because the first build failed: building [gcr.io/**/my-proj]: tagging: pushing: getting auth config for gcr.io/**/my-proj:3c275201-dirty-50f870d: getting auth config: error getting credentials - err: exec: \"docker-credential-gcr\": executable file not found in $PATH, out: ``"
```

possibly related: https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000464664-IDEA-sandbox-problems-with-shell-command

**Comment by etanshaul** [comment]
the reason this is happening is because `System.getEnv()` isn't returning the full path. This is because `.bash_profile` (or `.bashrc`) is changing the `PATH`.

**Comment by etanshaul** [comment]
yes, you're right. thanks for clarifying that.

**Comment by ivanporty** [comment]
Another update - if you start `runIde` from the terminal itself, the variables are correctly passed through:
```
./gradlew :runIde
```
It seems only to fail when we launch sandbox IDE from IDEA itself, and IDEA was itself launched from the desktop, not terminal.


This question is relevant as well:

**Comment by etanshaul** [comment]
yea that make sense because if you run it from the terminal that it will pick up the environment as set in `.bash_profile` / `.bashrc`.

I wonder though if it will work in normal / non-sandbox mode if you don't run it from the terminal?

**Comment by ivanporty** [comment]
Just tested:
so if you launch IDEA from the desktop, open Container Tools project, bash variables are not there, and many PATH elements are missing, such as gcloud.

But, if you launch it from a terminal, and then start sandbox from the IDE, it all works! I guess this is more of a IDE launch issue than an actual code issue.

**Comment by etanshaul** [comment]
@ivanporty 

I don't think there is a automated fix for this in the plugin. If the IDE isn't launched from bash then as far as I can tell there is no way to make the plugin aware the environment variables defined in `.bash_profile` / `.bashrc`.

In this scenario, the user would have to either add gcloud as a system wide environment variable (e.g. `/etc/environment`) or configure the standalone `docker-credential-gcr` to use instead of the gcloud bundled credential helper.

So as I see it we can solve this via documentation: e.g. have an FAQ section that details this scenario and how to work around it.

lmwyt and if you can think of any other alternatives

**Comment by ivanporty** [comment]
I agree, the only sane idea how to solve this for all possible environments and flavors of OS is probably mention in documentation that IDE started from desktop may not have all the terminal defined variables.

I suppose we can leave this issue open for now and treat this as documentation one?

**Comment by etanshaul** [comment]
yes. good idea. lets leave open

**Comment by etanshaul** [comment]
migrated to: https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/2394
