### ISSUE TITLE
Detect presence of Skaffold configuration file(s) and ask to create Skaffold run configuration

### ISSUE THREAD

**Issue by ivanporty** [GoogleContainerTools/google-container-tools-intellij#7]
If project is opened or new files appear, detect if Skaffold configuration YAML is present, and prompt a user to create Skaffold run configuration, using pop-up notification.

**Comment by etanshaul** [comment]
@ivanporty have you started on this one? I could start tackling it if not

**Comment by ivanporty** [comment]
I was thinking about getting it done soon, but not yet - please take it, that would be great!
