### ISSUE TITLE
Research better use for "skaffold fix" and schema updates

### ISSUE THREAD

**Issue by ivanporty** [GoogleContainerTools/google-container-tools-intellij#75]
Currently running fresh version of Skaffold on an older version/schema of `skaffold.yaml` results in a warning that schema has changed and suggestion to run `skaffold fix` on it. This is  not quite IDE friendly way and we should research and implement a better way to detect schema change and ask a user about upgrading it before actual deployment so the warning won't be necessary.

**Comment by etanshaul** [comment]
agree. just some thoughts: 

In the shorter term, what if we ran a `skaffold fix` before each deployment, and if there is an issue, print out the suggested yaml to the console for the user to update?

In the longer term, with schema integration as well as managed skaffold support we can likely mitigate this problem by pinning a skaffold installation to a particular known version and then load the appropriate schema for that version. We can then use this for editing warnings as well as more proactive notifications.

**Comment by ivanporty** [comment]
Update: skaffold team implemented in-memory "fix" for older schemas and will do conversion with a warning message, which makes it much easier for now for the plugin.

**Comment by etanshaul** [comment]
thats great. much easier

**Comment by ivanporty** [comment]
With the current way `skaffold fix` works, this issue seems not to be relevant anymore as it doesn't stop deployments to proceed.
